export const AGENT_CATALOG = {
  name: "Sonic CRM Agent API",
  basePath: "/api/v1",
  auth: "Authorization: Bearer <CRM_API_KEY>  or  X-API-Key: <CRM_API_KEY>",
  notes: [
    "This key controls the full CRM (leads, SMS, campaigns, scrape, inbox).",
    "Do not auto-send SMS to interested prospects unless the user asked you to send.",
    "Not-interested inbound SMS is already auto-handled by Gemini.",
  ],
  endpoints: [
    { method: "GET", path: "/api/v1", description: "This catalog" },
    { method: "GET", path: "/api/v1/health", description: "Liveness + which integrations are configured" },
    { method: "GET", path: "/api/v1/brief", description: "Daily operator brief (Gemini). Query refresh=1 to regenerate" },
    { method: "GET", path: "/api/v1/stats", description: "Dashboard counts" },
    { method: "GET", path: "/api/v1/leads", description: "List leads. Query: search, status, archived (false|true|all), unenrolled, page, limit" },
    { method: "POST", path: "/api/v1/leads", description: "Create lead. Body: phone (required), name, businessName, city, email, website, notes" },
    { method: "POST", path: "/api/v1/leads/import", description: "Bulk upsert. Body: { leads: [{ phone, businessName, name, city }] }" },
    { method: "GET", path: "/api/v1/leads/:id", description: "Lead + recent messages + pending suggestion" },
    { method: "PATCH", path: "/api/v1/leads/:id", description: "Update fields: status, notes, archived, name, businessName, city, email, website, phone" },
    { method: "DELETE", path: "/api/v1/leads/:id", description: "Delete lead" },
    { method: "GET", path: "/api/v1/inbox", description: "Latest inbound per prospect" },
    { method: "GET", path: "/api/v1/messages", description: "Query leadId to get a thread" },
    { method: "POST", path: "/api/v1/sms", description: "Send SMS. Body: { leadId, message, suggestionId? }" },
    { method: "GET", path: "/api/v1/replies", description: "Prospects who replied, with status/archive/messages" },
    { method: "GET", path: "/api/v1/suggestions", description: "Pending Gemini drafts. Query leadId optional" },
    { method: "PATCH", path: "/api/v1/suggestions/:id", description: "Body: { status: sent|dismissed }" },
    { method: "GET", path: "/api/v1/notifications", description: "Recent alerts" },
    { method: "PATCH", path: "/api/v1/notifications", description: "Body: { all: true } or { id }" },
    { method: "GET", path: "/api/v1/campaigns", description: "List drip campaigns" },
    { method: "POST", path: "/api/v1/campaigns", description: "Create. Body: { name, message, description? }" },
    { method: "PATCH", path: "/api/v1/campaigns/:id", description: "Update name/message/description" },
    { method: "DELETE", path: "/api/v1/campaigns/:id", description: "Delete campaign" },
    { method: "POST", path: "/api/v1/campaigns/:id/enroll", description: "Queue leads. Body: { leadIds: string[], count? }" },
    { method: "POST", path: "/api/v1/campaigns/:id/control", description: "Body: { action: pause|resume|stop }" },
    { method: "GET", path: "/api/v1/campaigns/:id/progress", description: "Drip queue progress" },
    { method: "POST", path: "/api/v1/scrape", description: "Run Finder Maps pipeline and save leads. Body: { prompt: 'Find 25 plumbers in Houston TX, under 150 reviews' }" },
    { method: "GET", path: "/api/v1/jobs", description: "Scrape job history" },
  ],
};
